[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
[etherscan]
blaze = { key = "${ETHERSCAN_API_KEY}", url = "https://rpc.blaze.soniclabs.com" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
